version: '3'
services:
  quotes:
    build:
      context: ./quote
      dockerfile: app.dockerfile
  api:
    build:
      context: ./gateway
      dockerfile: app.dockerfile
    environment:
      - "QUOTES_API=http://quotes:5000"
    depends_on:
      - quotes
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend
      dockerfile: app.dockerfile
    ports:
      - "8080:80"
    